version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rsp

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    image: nofutur3/php:7.2
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www
    command: ["php", "bin/console", "server:run", "0.0.0.0:8000"]
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/rsp
      MAILER_URL: smtp://emails:1025?encryption=&auth_mode=

  emails:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
